name: Assignment 1:Run Python Tests & Notify on Fail 🧪

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Run tests
        run: python -m unittest test_calculator.py

  # This is the new job you are adding
  notify-on-failure:
    runs-on: ubuntu-latest
    needs: build    # Ensures this job runs only AFTER the 'build' job is complete
    if: failure()   # The most important part: This job ONLY runs if the 'build' job fails
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          # The action uses the secrets you created to log in and send the email
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Build Failed: ${{ github.repository }}"
          to: ${{ secrets.MAIL_TO }}
          from: GitHub Actions <${{ secrets.MAIL_USERNAME }}>
          body: "The build for commit ${{ github.sha }} failed."
